export default {
  login: 'Urimzy',
  id: 100048070,
  node_id: 'U_kgDOBfacxg',
  avatar_url: 'https://avatars.githubusercontent.com/u/100048070?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Urimzy',
  html_url: 'https://github.com/Urimzy',
  followers_url: 'https://api.github.com/users/Urimzy/followers',
  following_url: 'https://api.github.com/users/Urimzy/following{/other_user}',
  gists_url: 'https://api.github.com/users/Urimzy/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/Urimzy/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Urimzy/subscriptions',
  organizations_url: 'https://api.github.com/users/Urimzy/orgs',
  repos_url: 'https://api.github.com/users/Urimzy/repos',
  events_url: 'https://api.github.com/users/Urimzy/events{/privacy}',
  received_events_url: 'https://api.github.com/users/Urimzy/received_events',
  type: 'User',
  site_admin: false,
  name: 'Urim',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: 'Remember my name.',
  twitter_username: null,
  public_repos: 5,
  public_gists: 0,
  followers: 2,
  following: 6,
  created_at: '2022-02-19T21:05:25Z',
  updated_at: '2023-03-28T20:07:40Z',
}
